# NOTES TEXTBOX VARIABLES
browser=    "chrome"
urlDemoQATextBox=    "https://demoqa.com/text-box"
urlDemoQACheckBox=    "https://demoqa.com/checkbox"
fullNameField=    "id=userName"
fullName=    "test"
emailField=    "id=userEmail"
emailUser=    "test@1secmail.com"
addressField=    "id=currentAddress"
addressUser=    "Jl. Jl. ke Pasar Baru"
permanentAddressField=    "id=permanentAddress"
permanentAddressUser=    "Jalan Jalan ke Pasar Senen"
submitText=    "#submit"
submitButton=    "id=submit"
outputText=    "id=output"
homeButton=    "class=rct-title"
resultText=    "id=result"
