# NOTES TEXTBOX VARIABLES
browser=    "chrome"
url_demoqa=    "https://demoqa.com/text-box"
fullNameField=    "id=userName"
fullName=    "test"
emailField=    "id=userEmail"
emailUser=    "test@1secmail.com"
addressField=    "id=currentAddress"
addressUser=    "Jl. Jl. ke Pasar Senen"
permanentAddressField=    "id=permanentAddress"
permanentAddressUser=    "Jalan Jalan ke Pasar Senen"
submitButton=    "id=submit"
outputText=    "id=output"
